@startuml
skinparam defaultFontName "WenQuanYi Zen Hei"
skinparam shadowing false
left to right direction

actor 用户 as user
actor 群主 as owner

rectangle "出行规划管理" {
  usecase "成员约束管理" as p1
  usecase "初始方案生成" as p2
  usecase "行程节点管理" as p3
  usecase "地图路线导航" as p4
  usecase "预算费用管理" as p5
}

user --> p1
user --> p2
user --> p3
user --> p4
user --> p5
owner --> p2
@enduml
