@startuml
skinparam defaultFontName "WenQuanYi Zen Hei"
skinparam shadowing false
left to right direction

actor 管理员 as admin

rectangle "后台与监控管理" {
  usecase "用户管理" as b1
  usecase "运营后台管理" as b2
  usecase "数据统计分析" as b3
}

admin --> b1
admin --> b2
admin --> b3
@enduml
