@startuml
skinparam defaultFontName "WenQuanYi Zen Hei"
skinparam shadowing false
left to right direction

actor 用户 as user
actor 群主 as owner

rectangle "社交组队管理" {
  usecase "好友关系管理" as s1
  usecase "出行小组管理" as s2
  usecase "房间码加入" as s3
}

user --> s1
user --> s2
user --> s3
owner --> s2
@enduml
