@startuml
skinparam defaultFontName "WenQuanYi Zen Hei"
skinparam shadowing false
left to right direction

actor 用户 as user

rectangle "账号管理" {
  usecase "注册和登录" as a1
  usecase "注销" as a2
  usecase "个人资料管理" as a3
}

user --> a1
user --> a2
user --> a3
@enduml
